# This is a config for E2B sandbox template.
# You can use template ID (4moqrsp4oz5xg6o2prt3) or template name (vibe-nextjs-deepanshu-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-deepanshu-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-deepanshu-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-deepanshu-1')

team_id = "d48db272-71f3-42a2-851d-3454c6480caa"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-deepanshu-1"
template_id = "4moqrsp4oz5xg6o2prt3"
